services:
  # Backend API
  - type: web
    name: time-bucket
    runtime: ruby
    region: singapore
    plan: free
    rootDir: backend
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: time-bucket-postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: FRONTEND_URL
        value: https://time-bucket.yminamiyama.com
      - key: RAILS_ENV
        value: production
      - key: RAILS_LOG_TO_STDOUT
        value: enabled
      - key: RAILS_SERVE_STATIC_FILES
        value: enabled
      - key: GOOGLE_OAUTH_CLIENT_SECRET
        sync: false
      - key: GOOGLE_OAUTH_CLIENT_ID
        sync: false

databases:
  # PostgreSQL
  - name: time-bucket-postgres
    region: singapore
    plan: free
    databaseName: prd_time_bucket_db
    user: prd_time_bucket_db_user
